import { Property } from '@/types/property'

export const mockProperties: Property[] = [
    {
        id: '1',
        title: 'Cozy Apartment in Downtown',
        description: 'A cozy apartment located in the heart of the city, close to all amenities.',
        type: 'condo',
        status: 'for_sale',
        price: 1200,
        area: 1000,
        bedrooms: 2,
        bathrooms: 2,
        province: 'Ontario',
        district: 'Toronto',
        lat: 43.6532,
        lng: -79.3832,
        images: ['https://placehold.co/600x400.jpg'],
        agentId: 'agent1',
        createdAt: new Date(),
        views: 150,
    },
    {
        id: '2',
        title: 'Spacious House in Suburbs',
        description: 'A spacious house located in a quiet suburb, perfect for families.',
        type: 'house',
        status: 'for_rent',
        price: 2500,
        area: 2000,
        bedrooms: 4,
        bathrooms: 3,
        province: 'Ontario',
        district: 'Mississauga',
        lat: 43.5890,
        lng: -79.6441,
        images: ['https://placehold.co/600x400.jpg'],
        agentId: 'agent2',
        createdAt: new Date(),
        views: 200,
    },
]