import { Property } from '@/types/property'

export const mockProperties: Property[] = [
    {
        id: '1',
        title: 'Skyline Condo near Phrom Phong',
        description: 'A bright high-floor condo with city views, a practical work corner, and direct access to restaurants, parks, and BTS Phrom Phong.',
        type: 'condo',
        status: 'for_sale',
        price: 6800000,
        area: 54,
        bedrooms: 2,
        bathrooms: 2,
        province: 'Bangkok',
        district: 'Watthana',
        lat: 13.7308,
        lng: 100.5697,
        images: [
            'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=900&q=80',
            'https://images.unsplash.com/photo-1560184897-ae75f418493e?auto=format&fit=crop&w=900&q=80',
        ],
        agentId: 'agent1',
        createdAt: new Date(),
        views: 150,
    },
    {
        id: '2',
        title: 'Family House with Garden in Ari',
        description: 'A quiet detached house designed for family routines, with a shaded garden, open kitchen, and flexible room for an office or nursery.',
        type: 'house',
        status: 'for_rent',
        price: 85000,
        area: 220,
        bedrooms: 4,
        bathrooms: 3,
        province: 'Bangkok',
        district: 'Phaya Thai',
        lat: 13.7801,
        lng: 100.5446,
        images: [
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80',
        ],
        agentId: 'agent2',
        createdAt: new Date(),
        views: 200,
    },
    {
        id: '3',
        title: 'Townhome near Ratchada Offices',
        description: 'A renovated townhome with three usable floors, covered parking, and fast access to MRT, shopping malls, and office districts.',
        type: 'townhouse',
        status: 'for_sale',
        price: 11900000,
        area: 168,
        bedrooms: 3,
        bathrooms: 4,
        province: 'Bangkok',
        district: 'Huai Khwang',
        lat: 13.7767,
        lng: 100.5731,
        images: [
            'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1600210491369-e753d80a41f3?auto=format&fit=crop&w=900&q=80',
        ],
        agentId: 'agent3',
        createdAt: new Date(),
        views: 86,
    },
    {
        id: '4',
        title: 'Riverside Land Plot in Nonthaburi',
        description: 'A rare land plot with river access, suitable for a private residence or small hospitality project outside the busiest city core.',
        type: 'land',
        status: 'for_sale',
        price: 18500000,
        area: 640,
        bedrooms: 0,
        bathrooms: 0,
        province: 'Nonthaburi',
        district: 'Pak Kret',
        lat: 13.9125,
        lng: 100.5021,
        images: [
            'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
        ],
        agentId: 'agent4',
        createdAt: new Date(),
        views: 64,
    },
]
